### ISSUE TITLE
Make annotation source discoverable

### ISSUE THREAD

**Issue by pspacek** [icann/rfc-annotations#106]
Use case: I want to modify existing annotation.

Current display:
![screenshot](https://user-images.githubusercontent.com/11509590/189906347-b982af6a-fee8-416f-803d-e61b993d6b4c.png)

Now I'm faced with question: Where the annotation came from?

Accidentally I happen to know it comes from repo https://github.com/icann/icann-annotations/tree/main/icann-updates , but I still have to grep for the right file. It would be more expedient if the generated annotation contained a link with URL for the source file.

I think just something subtle like an icon hyperlinked to the source file would work.

**Comment by paulehoffman** [comment]
This is an interesting idea. @reschke, is this feasible in the short term?

Not all source files will have URLs associated with them because they might have been gotten with rsync, but I expect most will come from https: to git repos.

**Comment by pspacek** [comment]
I think it is fine if the URL is not HTTP url - `rsync://something` is also okay. (I expect) Often users will just hover over the link, slap itself on forehead and exclaim "sure!" and that will be it.

**Comment by reschke** [comment]
Even for git it's not trivial; we'd need to find the git config, then deduce an HTTPS URI from that.

**Comment by pspacek** [comment]
Again, I don't think we need fully correct URL. I just want to see "something".

**Comment by pspacek** [comment]
Oh, maybe we don't need to be fixated to URL format at all? Maybe icon with tooltip (no promises to make it URL/clickable)?

**Comment by paulehoffman** [comment]
@reschke : is it easy to know/remember the URL to the git repo? (Or, for the edge case, the rsync URL?)

**Comment by reschke** [comment]
I don't think so - at least without making assumptions how to get from "git:" to "https:".

**Comment by paulehoffman** [comment]
A possible design would be for the annotations processor to make a giant file of all the annotations it has processed, make it HTML with lots of links and so on, put that file in the same directory as the annotated RFCs, and the link you desire would go to that file. That file could at least show the URL used to pull the annotations.

This would likely be too big for us to get into the release in a few weeks, but should eventually work as a feature.

**Comment by paulehoffman** [comment]
This is complicated by the fact that we traverse down directories, so just the annotation source URL and the filename is not sufficient. It would also need to be a full file path.

**Comment by reschke** [comment]
What should be simple is remembering the relative path this came from. Not sure how to expose it in the HTML though (unless something that requires "view source" is acceptable :-)

**Comment by paulehoffman** [comment]
You're right, we don't really need to show the source, just the path, to meet the need expressed at the beginning of this thread.

**Comment by mboe** [comment]
If the changes in PR#110 are not sufficient please let me know otherwise this issue can be closed, right?

**Comment by paulehoffman** [comment]
Sorry, I missed this. Yes, #110 fixed this.

**Comment by pspacek** [comment]
I apologize for not responding in timely manner. I just had look at live instance https://rfc-annotations.research.icann.org/rfc1034.html and it works fine. Thank you!
