### ISSUE TITLE
Can't check state of draft ...

### ISSUE THREAD

**Issue by paulehoffman** [icann/rfc-annotations#107]
```
   Warning:
Can't check state of draft 'draft-ietf-dnsop-caching-resolution-failures-01'. Will be skipped.
```
@mboe : Can you tell what the reason for this is? It would be nice for us to help the IETF folks fix their database if the problem is on their side.

**Comment by mboe** [comment]
Should be gone with the changes contained in the PR. We do use cached draft status information which have not been automatically invalidated if newer annotations have been `rsync`ed.
