### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by paulehoffman** [icann/rfc-annotations#118]
We should have a favicon for every page because some browsers (like Safari) will attach a favicon based on a previously-seen favicon from a shorter domain. Safari shows the ICANN favicon while Chrome and Firefox does not. My proposal is that if there is a favicon.ico file in local-config/, add it to every page being created with "make" (both the RFCs and the index page).

It does not appear sufficient to put a favicon.ico in the home directory if the browser has ever cached the favicon. Thus, this needs to be put as a `link` resource in every page.

@reschke @mboe

**Comment by mboe** [comment]
I made some tests and it seems that this is possible without any changes to the project. We have a file `css.html` and its content is injected into the _header_-area of all generated html files. If you want to point to a specific favicon you have to

1.  deploy this icon to your Webserver (it will not work using the file urls). Remember the url.
2. add a line like `<link rel="icon" href="https://my.domain/my.path/myicon.png" />` (actually use the url above) to the beginning of the `css.html`. It seems reasonable that this line is actually the first line of the `css.html`.
3. re-created the output performing a `make`
4. re-deploy the generated html files to your Webserver.

I observed that Safari caches the favicon meta information. I had to close and open Safari every time I made changes. Furthermore I had to use urls located on the same host. Cross-referencing other domains did not work.

**Comment by mboe** [comment]
Please test and let me know whether this fulfills your requirements.

**Comment by paulehoffman** [comment]
This does indeed work fine. Thus, I'm closing the issue and do not need any code changes for it.
