### ISSUE TITLE
Generated files pointing back at the generated index

### ISSUE THREAD

**Issue by paulehoffman** [icann/rfc-annotations#119]
RFC pages should point back to the index page in a very obvious fashion so that if someone gets a URL to an RFC page, they can go to the main index page and see our explanation. My proposal is that if there is a top-annotation.txt file in local-config/, "make" turns that into an annotation for line 1, and that annotation appears first before any of the other line 1 annotations.

@reschke @mboe

**Comment by paulehoffman** [comment]
I merged the PR, but in talking to my boss, this isn't sufficient to fix the problem we have where someone gets a URL to one of our RFCs and having an obvious way to get back to the home page where the RFC originated. Is it hard to do add an annotation at the top of the list of annotations?

**Comment by mboe** [comment]
Please see https://github.com/icann/rfc-annotations/pull/121

**Comment by paulehoffman** [comment]
Thanks, that's perfect.
