### ISSUE TITLE
All customization must survive a `git pull`

### ISSUE THREAD

**Issue by mboe** [icann/rfc-annotations#12]
(originally created by @paulehoffman):
Currently, if I edit `rfcs-to-use.txt` and then do a `git pull`, I will need to do some merging dance. Telling the user to use some environment variable to prevent this is unfriendly. We need a design that allows the easy changing of `rfcs-to-use.txt` and still allow updates via git.

The same issue exists with the new `annotations/rfc-config.txt` file.

A possible design: create a `config/` dir that is empty.

- When looking for `rfcs-to-use.txt`, if it exists in `config/`, use that instead.
- When looking for `annotations/rfc-config.txt`, also look for `config/rfc-config.txt` and add anything there to the list of annotations gotten.
- When looking for `scripts.html` and `css.html`, if those files exist in `config/`, add the material from them to the main material.

There might be more.

**Comment by paulehoffman** [comment]
This is now even more important with us editing `rfcs-to-use.txt` to have header information. It is quite believable that someone would want to toss their own notes in there, and would be sorely bummed if those notes disappeared when they did a `git pull`.

**Comment by mboe** [comment]
I think that we can't easily solve the basic problem that we and the user want to change/expand/modify the same things. Furthermore, with every user change it is not obvious whether this change should replace our defaults or should be used additionally (in whatever form). You mentioned the difference yourself in several places (`rfcs-to-use.txt` is to replace, `css.html` is to be used in addition if necessary). An implicitly different behavior, depending on the file, I find quite confusing and intransparent.

The mechanism I provided for NOT having to merge is to set the information given by the user in an environment variable. This overwrites everything and nothing has to be merged. Furthermore, the user can always see what was actually intended by us. I find this transparent and convenient as long as we are not supposed to merge information (CSS was a good example.) This can be addressed by inventing something like EXTRA_CSS (and EXTRA_SCRIPTS etc.) environment variables which will be automatically merged into the generated output by the code.

**Comment by mboe** [comment]
As mentioned in our `README.md`: 

> The programs ... allow user configuration through environment variables.

My hypothesis is that if we continue down this path consistently, we can get around the above problems, since the delivered files are not overwritten by the user.

**Comment by paulehoffman** [comment]
Reopening because, while this works, it is not sufficient to fix the problem in my mind.

**Comment by reschke** [comment]
This is tricky, because the extensibility models are not the same.

Let's start with rfcs-to-use...:

Potential modifications:

1. Replacement ("I want to do this for HTTP")
2. Adding RFC numbers
3. Removing RFC numbers
4. Changing the boilerplate HTML

I would argue that throwing in the boilerplate into the list was a hack, and we should have a separate file for that.

For the other three points I can imagine a syntax that allows deleting everything, deleting single entries, and adding new entries (essentially a simple "patch" format).

Maybe we can focus on this one first, and then see how the solution maps to other extension points?

**Comment by reschke** [comment]
Trying to summarize from call with @paulehoffman...

- all config files will have the same extensibility model ("replace")
- there'll be a folder for local config files ("local-config")
- if a file is found there, the default is ignored

As a bonus, we can check somewhere (during make?) whether a checked-in config file has changed (simply compare dates with local-config/*), in which case we can show the diff and remind the user that they might have to update their local config (..."If you do not want to update your config, nor see this message, just 'touch' your config file")

**Comment by paulehoffman** [comment]
I'll add one more thing here, and then I think it's complete and consistent: all default config goes into a folder called "default-config". That is, move `annotations/rfc-config.txt`, `css.html`, `scripts.html`, and `rfcs-to-use.txt` (which will become `dns-rfcs.txt`) into `default-config/`, look there when running `make`, but also look in `local-config/` and if you find any of those files there, ignore the matching one in `default-config/`.

**Comment by paulehoffman** [comment]
Also, `rfc-config.txt` does not really indicate that this is annotation sources. That file should be renamed to `annotation-sources.txt`.

**Comment by mboe** [comment]
I've implemented most of the desired behavior but I'd like to wait until https://github.com/icann/rfc-annotations/pull/41 is merged (otherwise there will be lots of merge conflicts).

@paulehoffman  I do have one open question: What is the desired location of `annotation-sources.txt`? Shall it remain in the `annotation` folder or be moved to `global-config` (with an optional to-be-used copy in `local-config`)?

**Comment by paulehoffman** [comment]
#41 is now merged.

`annotation-sources.txt` should be in `global-config/` and replaced in `local-config/`. That makes all configs appear in the same place(s).

**Comment by mboe** [comment]
Please note that according to the changes `index.html` is now `dns-index.html`.

**Comment by paulehoffman** [comment]
@mboe : when I copy `dns-rfcs.txt` into `local-config/` and do a small edit on it, then run `make` again, `make` appears to run twice. Are you checking for the existence of `dns-rfcs.txt` in `local-config/` late?

**Comment by mboe** [comment]
args. Will check and change.

**Comment by mboe** [comment]
Please merge https://github.com/icann/rfc-annotations/pull/45

**Comment by mboe** [comment]
@paulehoffman can we close this ticket or is there still something open?
