### ISSUE TITLE
rfc-index.xml is not updated

### ISSUE THREAD

**Issue by paulehoffman** [icann/rfc-annotations#122]
Using `make`, rfc-index.xml is not updated. To get it updated, I need to remove the file before an update.

**Comment by reschke** [comment]
That is IMHO the intention.

The file is currently at 13 MB, and refetching it too often doesn't sound like a good idea. "make clean" or manually removing it doesn't sound like a problem to me.

Or are you saying that we should do an up-to-date check, or fetch it at least once in x days?

**Comment by paulehoffman** [comment]
The problem comes from adding a newly-issued RFC to the `dns-rfcs.txt` file. Running `make` after that fails because the added RFC does not appear in the XML file. 

One possibility is to pull the XML file and restart if there is a "RFC not found in index" error. That might be too fiddly. Other than that, I would say that even though the file is large, it can be pulled when there RFCs are pulled.
