### ISSUE TITLE
Locate where annotations go by text fragment

### ISSUE THREAD

**Issue by paulehoffman** [icann/rfc-annotations#18]
A third alternative to `#L` and `#S` is `#F` that has a text fragment that can be found in the RFC.

If the fragment can't be found, it is an error.

If the fragment exists in multiple places, use the first.

**Comment by reschke** [comment]
Sounds good.

**Comment by mboe** [comment]
The proposed solution embedded in the PR will find the text fragments regardless of their position in the text file. 

The target text in the textual representation of the RFC may be split into two lines. The fragment will be found anyway. More complex fragments split into three lines or more are not supported. 

In the modern versions of the RFCs (not containing page breaks anymore) sometimes additional `|` characters are inserted (marking block quotes) after artificially generated line breaks. These characters are ignored comparing the text fragment. You can specify the desired text without taking care of line breaks or these block quote markers.
