### ISSUE TITLE
Viewing just annotations

### ISSUE THREAD

**Issue by paulehoffman** [icann/rfc-annotations#19]
There should be a way to see all the annotations for an RFC at once. This would allow the reader to not have to scroll through the whole RFC to know how many, and of what type, are in the RFC.

I can see at least two ways of doing this, but am open to others as well.

1) Some CSS/JSS magic to cause all the annotations to jump to the top of the doc. I am skeptical that this is possible.

2) A second file that is just annotations. The file would be linked to in another column in index.html. Every annotation in that file would have a link to the annotation in the main generated RFC.

**Comment by reschke** [comment]
1. might be easy by toggling the visibilty of the spec text.
2. should be easy too

**Comment by mboe** [comment]
It's no big deal (minor code change and add css like this `.area pre.rfc {display: none;}`. The bigger question is how we want to get to this mode? Add some static buttons to the top of the page or a floating area or something completely different?

**Comment by reschke** [comment]
if this is the only toggle we need, a button might be the way to go.

**Comment by mboe** [comment]
Please try my proposal.

**Comment by paulehoffman** [comment]
Excellent, thanks!
