### ISSUE TITLE
Multiple RFC lists

### ISSUE THREAD

**Issue by paulehoffman** [icann/rfc-annotations#2]
It is likely that groups other than "the DNS world" will want to use this tool. We should think how there can be more than one RFC list, and that a single user should be able to get access to all of them.

**Comment by reschke** [comment]
We have a script that sets RFC lists for various topics, such as HTTP.

The user could then just say

~~~
export RFC_LIST=HTTP_RFC_LIST
~~~

for instance.

**Comment by paulehoffman** [comment]
@reschke and I agreed that a way to do this would be:

- change the name of `rfcs-to-use.txt` to `<name>-rfcs.txt`
- generate `generated/<name>-index.html`
- `make` looks for any `*-rfcs.txt` file in the main directory (and in the subdirectory from #12) and generates multiple indexes if the user has them

**Comment by paulehoffman** [comment]
Assigning to @mboe

**Comment by mboe** [comment]
@paulehoffman IMHO this ticket can be closed
