### ISSUE TITLE
usage of `@@` syntax in `<pre>` sections is broken

### ISSUE THREAD

**Issue by mboe** [icann/rfc-annotations#25]
Defining references to RFCs using the `@@`RFC_NR`@@` syntax inside a `<pre>` section produces warnings and broken output.

**Comment by reschke** [comment]
FWFW, any chance we could have a "@@" syntax allowing to link to specific sections as well?

**Comment by mboe** [comment]
yes, we can. What about `@@RFC_NR#<Ref>@@` where _<Ref>_ is something like `line-1`, `section-1` or just `1` (same as `section-1`)? We can enhance this by skipping the `RFC_NR` for creating convenient links inside the document.

**Comment by reschke** [comment]
I would standardize on something more readable:

~~~
@@RFC1234@@
@@Section x.y of RFC1234@@
@@line NNNN in RFC1234@@
~~~

**Comment by reschke** [comment]
This doesn't seem to be  ... complete.

First of all, when the contents between the "@@" doesn't match the supported patterns, it shouldn't generate a link (and maybe generate a warning).

Second, for the use in errata annotations, I'd like to see support for common patterns used in the errata notes (unless we're ok with errata edits that change more than formatting - @paulehoffman - question for you).

Proposed formats would be:

~~~
WSP = <whitespace>
SECTIONNUMBER = ( "Appendix" / "Section" ) 1*WSP  1*("0-9" / "A-Z" / ".")
RFCNO = "[RFC" 1*DIGIT "]" / "RFC" 1*DIGIT
fmt1 = SECTIONNUMBER 1*WSP "of" 1*WSP RFCNO 
fmt2 = RFCNO *WSP "," 1*WSP SECTIONNUMBER 
~~~

where "\*WSP" is optional whitespace, "1*WSP" one or more whitespace chars, and string constants are case-insensitive.

Then link RFCNO to the datatracker overview page, and SECTIONNUMBER to the section in the HTML rendition.
