### ISSUE TITLE
discuss how eclipsed errata shall be handled

### ISSUE THREAD

**Issue by mboe** [icann/rfc-annotations#29]
Previously we had an `errata.patch` file containing fixes to invalid details stored in an (immutable) errata file. This was mainly used to fix invalid section references. In the meantime, the content of the `errata.patch` was removed and all errata files containing errors have been duplicated (to be clear: the associated annotation file of the erratum has been duplicated) and corrected. These annotation files are located in a separate git repository and will be used when running our tool. The tool itself identifies whether the original errata (annotation) files have been eclipsed by the manually corrected files described above. Usually the original, eclipsed errata annotations are **NOT** shown.

However, this is only the default. You can override this by adding special css. Doing so, the original erratum is shown, too.

Therefore all `_generated` annotations are handled, regardless, whether they are eclipsed or not. Therefore invalid `section` references are printed, if not fixed by the `errata.patch` file.

We have to decide how we'd like to handle this situation. We can:

1. drop the handling of all eclipsed errata annotation files
2. resurrect the content of the `errata.patch` file
3. drop the warnings for annotations which are eclipsed 
4. do something else

**Comment by reschke** [comment]
2. does not work IMHO, it causes the updated errata annotations to say "based on outdated version"

3. works for me

1. works for me, too, as we're linking to the original erratum anyway

**Comment by mboe** [comment]
@reschke is your numbering correct (starts with `2`)?

**Comment by reschke** [comment]
yes

**Comment by reschke** [comment]
@paulehoffman - would you be ok with just dropping the eclipsed errata (not having them in the HTML, hidden by CSS)? After all - we are linking to them anyway.

**Comment by paulehoffman** [comment]
Yes, it's OK to drop them.

**Comment by mboe** [comment]
@paulehoffman IMHO this ticket can be closed as soon as https://github.com/icann/rfc-annotations/pull/48 is merged
