### ISSUE TITLE
Stop reporting when sections cannot be created

### ISSUE THREAD

**Issue by paulehoffman** [icann/rfc-annotations#31]
Currently, `make annotations` reports things like the following in a few places:
```
Error: annotations for RFC1123 have 8 INVALID sections ('section-2.1', 'section-6.1.3.6', 'section-3.2.1', 'section-4.1.2.6', 'section-4.1.2.5', 'section-id 1081', 'section-2.5', 'section-5.2.2')!
```
That is not actionable, and can thus not be emitted.

@mboe

**Comment by mboe** [comment]
@paulehoffman  This is the output due to the changed `errata.patch` file. Please see https://github.com/icann/rfc-annotations/issues/29. As soon as we decide what to do, this output will probably vanish. IMHO this is a duplicate ticket for the same issue.

**Comment by mboe** [comment]
ok, after removing the _eclipsed_ versions of the errata (see #29), *four* annotations are remaining which have to be fixed (eg. by adding a corrected version to the `from-icann/icann-errata` directory. These are:

1. `RFC1123`, erratum `2464`: The section `4.1.2.6` does not exist as a html id in the HTMLized file. We should reference to `line-1669` instead.
2. `RFC1123`, erratum `1081`: The section `2.1` does not exist (see above)
3. `RFC1123`, erratum `1353`: The section `2.1, id 1081` is invalid.
4. `RFC5155`, erratum `3479`: The section `99 appendix a` does not exist.

@reschke can you please add/fix the errata files?

**Comment by reschke** [comment]
@mboe - we didn't have these updated as they are in the errata state "rejected" - maybe we should just skip those when generating warnings

**Comment by mboe** [comment]
currently it's only a question of the CSS whether we display these annotations or not. It we display the annotations they can not be positioned properly.

**Comment by reschke** [comment]
Question for @paulehoffman - do we care whether certain rejected errata display in the right location in case somebody decides to change the default CSS in order to display them?
