### ISSUE TITLE
demo support for HTTP RFCs

### ISSUE THREAD

**Issue by reschke** [icann/rfc-annotations#51]

**Comment by reschke** [comment]
Here's an initial "local-config/http-rfcs.txt":

~~~
1945
2109
2145
2616
2617
2817
2818
2965
3230
5789
6265
6266
6585
7230
7231
7232
7233
7234
7235
7236
7237
7238
7240
7538
7540
7541
7615
7616
7617
7639
7694
7725
7807
7838
8164
8187
8188
8246
8297
8336
8441
8470
8586
8673
8740
8941
8942
9110
9111
9112
9113
9114
9204
9205
9209
9211
9213
9218
9220
~~~

(this includes almost everything except WebDAV).

Q1: where would we put this?
Q2: once I start editing errata, where should they go? Separate annotations repo owned by me?

**Comment by paulehoffman** [comment]
Q1: Host it on a greenbytes repo. Once you have done a fair number of hand-curated errata and other annotations, I'll mention that location in the main README

Q2: Also in a greenbytes repo. It would work to have http-rfcs.txt be in the main directory, and a subdirectory for annotations.

**Comment by reschke** [comment]
Work started at https://github.com/greenbytes/http-rfc-annotations
