### ISSUE TITLE
proposed regexps to  match contents of "@@" pairs

### ISSUE THREAD

**Issue by reschke** [icann/rfc-annotations#57]
Plan:

1. find pairs of  "@@"
2. match contained text against three regexps, sequentially
3. regexp groups will give us "Section" vs "Line", Section number of line number, and RFC number
4. if nonmatch, continue (potentially using second "@@" as start)

The regexps match a sequence of groups; for each I'll specify the generated HTML.

Regexps, tested at https://regex101.com/:

~~~
"((Section|Appendix|Line)\s*([0-9A-Z\.]+))(\s*(of|in)\s*\[?)(RFC\s*([0-9]+))(\]?)"gmi
~~~
https://regex101.com/r/ZHUsaQ/3

Extract:

- section-or-line-number: group 3
- section-or-line-text: group 1
- section-or-line-type: group 2
- plain-text-1: group 4
- rfc-number: group 7
- rfc-text: group 6
- plain-text-2: group 8

Compute:

- section-or-line-target: deep link into HTML (local or on datatracker)
- rfc-target: link to datatracker page for the RFC (I assume)

Generate:
~~~
<a href="$section-or-line-target" _target="_blank">$section-or-line-text</a>$plain-text-1<a href="$rfc-target" target="_blank">$rfc-text</a>$plain-text-2
~~~

~~~
"(\[?)(RFC\s*([0-9]+))(\]?,\s*)((Section|Appendix|Line)\s*([0-9A-Z\.]+))"gmi
~~~
https://regex101.com/r/KqSWTL/2

Extract:

- plain-text-1: group 1
- rfc-text: group 2
- rfc-number: group 3
- plain-text-2: group 4
- section-or-line-number: group 7
- section-or-line-text: group 5
- section-or-line-type: group 6

Generate:
~~~
$plain-text-1<a href="$rfc-target" target="_blank">$rfc-text</a>$plain-text-2<a href="$section-or-line-target" _target="_blank">$section-or-line-text</a>
~~~

~~~
"(\[?)(RFC\s*([0-9]+))(\]?)"gmi
~~~
https://regex101.com/r/THdxye/2

Extract:

- plain-text-1: group 1
- rfc-text: group 2
- rfc-number: group 3
- plain-text-2: group 4

Generate:
~~~
$plain-text-1<a href="$rfc-target" target="_blank">$rfc-text</a>$plain-text-2
~~~

**Comment by mboe** [comment]
ok, I'll try to implement these

**Comment by reschke** [comment]
and, if possible, hyperlink the section/line number separately from the RFC number...

**Comment by mboe** [comment]
the PR https://github.com/icann/rfc-annotations/pull/58 should contain all necessary changes

**Comment by mboe** [comment]
@reschke please close if current implementation is sufficient or add infos otherwise. Thanks.

**Comment by reschke** [comment]
Updates to use named groups:

https://regex101.com/r/ZHUsaQ/4
https://regex101.com/r/KqSWTL/3
https://regex101.com/r/THdxye/3
