### ISSUE TITLE
embed new `-rfcs.txt` in annotation-repository

### ISSUE THREAD

**Issue by mboe** [icann/rfc-annotations#59]
As we can see embedding the https://github.com/greenbytes/http-rfc-annotations.git repository two steps are necessary in order to create an annotated list of RFCs (and its corresponding `index.html`).

1. embed the repository in the `annotation-source.txt`
2. manually copy the `*-rfcs.txt` file to your `local-config` directory.

I'd like to improve this by
a) extend the scope of the `-rfcs.txt`scan and search in the  `annotations` directory recursively, too
b) copy an existing `-rfcs.txt` file in the git repository to the `local-config` if a `git clone` or `git pull` is performed by the `pull_updates.py` code.

@paulehoffman What do you think?

**Comment by paulehoffman** [comment]
See my comment on the PR. I think this is a bad idea because it will surprise users who embed annotation repos from other people.

It is not a big deal for someone to create a new file in local-config/.
