### ISSUE TITLE
"potentially updated" vs expired/abandoned drafts

### ISSUE THREAD

**Issue by reschke** [icann/rfc-annotations#96]
Example:

  https://datatracker.ietf.org/doc/draft-karcz-uuas/

claims to update rfc 7231. It hasn't been updated since 2015 (and, fwiw, even if approved wouldn't update rfc 7231).

Should we remove the annotation for expired drafts? Or maybe for abandoned drafts that have expired a long time ago?

**Comment by paulehoffman** [comment]
Interesting question. Yes, let's only do "potentially updated" for drafts that are active or expired within the last six months.

**Comment by reschke** [comment]
Looking at potential states:

1. Active
2. Expired
3. In IESG processing...
4. RFC
5. Replaced
6. Withdrawn

Of these, we should ignore:

- states "RFC", "Replaced", "Withdrawn"
- otherwise, when "Active" or "Expired" and older than one year

("in IESG processing" I would always keep, no matter how old)

**Comment by mboe** [comment]
After applying the PR mentioned above you have to perform a `make clean` or a `rm annotations/_generated/*`. Otherwise the already created status annotations will be found anyway.
