### ISSUE TITLE
font size for annotations is way too small

### ISSUE THREAD

**Issue by reschke** [icann/rfc-annotations#97]
I assume that this was so that things work better on mobile devices, but displaying at 80% of the base font size doesn't work for me. IMHO, the annotations is why people will look at these documents, so they need to be readable.

**Comment by paulehoffman** [comment]
This sounds right to me as well. Mobile devices is an edge case for usage.

**Comment by mboe** [comment]
As discussed: @reschke, please change CSS and created a PR.

**Comment by reschke** [comment]
Will do.
